version: '3.8'

services:

  jobs:
    build_and_push:
      runs-on: ubuntu-latest
      steps:
        - name: clone code
          uses: actions/checkout@v2
        - name: docker build
          run: docker build -t lenzikeva/skypro_eportnova:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
        - name: docker login
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: docker push
          run: docker push lenzikeva/skypro_eportnova:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_diploma_12_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      timeout: 3s
      retries: 10
      interval: 3s

  api:
    image: iyamov/diploma_12:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - django_static:/opt/static

  bot:
    image: iyamov/diploma_12:latest
    env_file: .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
    command: python ./manage.py runbot

  frontend:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static

volumes:
  pg_diploma_12_data:
  django_static: